# Generated by Django 6.0.7 on 2026-08-10 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiendalibre', '0002_categoria_alter_producto_options_producto_activo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
    ]
